version: '3.8'

services:

  engi:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: engi
    environment:
      - VIRTUAL_HOST=engineer.nitk.ac.in
      - VIRTUAL_PORT=80
    networks:
      - nginx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./certs:/etc/nginx/certs
    networks:
      - nginx-network
    depends_on:
      engi:
        condition: service_healthy
    restart: unless-stopped

networks:
  nginx-network:
    driver: bridge
    name: nginx-proxy-network